[package]
name = "hifive1"
version = "0.2.0"
repository = "https://github.com/riscv-rust/hifive1"
authors = ["David Craven <david@craven.ch>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Board support crate for HiFive1 and LoFive boards"
keywords = ["riscv", "register", "peripheral"]
license = "ISC"

[dependencies]
riscv = "0.4.0"
riscv-rt = "0.4.0"
e310x-hal = "0.3.0"

[features]
board-hifive1 = []
board-lofive = []

[package.metadata.docs.rs]
features = ['board-hifive1']
